//
//  FaceBlendShapeView.swift
//  Blendshape2Robot
//
//  Created by liu on 2023/02/17.
//

import SwiftUI

struct FaceBlendShapeView: View {
    @EnvironmentObject var arViewModel: ArViewModel
    
    var body: some View {
        Grid {
            Group {
                Group {
                    GridRow {
                        Text("BrowOuterUpLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.browOuterUpLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("BrowOuterUpRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.browOuterUpRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("BrowInnerUp: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.browInnerUp.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("BrowDownLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.browDownLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("BrowDownRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.browDownRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                }
                Divider().gridCellUnsizedAxes(.horizontal)
                Group {
                    GridRow {
                        Text("EyeBlinkLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeBlinkLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("EyeBlinkRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeBlinkRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("EyeWideLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeWideLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("EyeWideRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeWideRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("EyeLookUpLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookUpLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("EyeLookUpRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookUpRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("EyeLookDownLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookDownLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("EyeLookDownRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookDownRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("EyeLookInLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookInLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("EyeLookInRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookInRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("EyeLookOutLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookOutLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("EyeLookOutRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeLookOutRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("EyeSquintLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeSquintLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("EyeSquintRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.eyeSquintRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                }
            }
            Divider().gridCellUnsizedAxes(.horizontal)
            Group {
                GridRow {
                    Text("NoseSneerLeft: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.noseSneerLeft.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                    Text("NoseSneerRight: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.noseSneerRight.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                }
                GridRow {
                    Text("CheekPuff: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.cheekPuff.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                }
                GridRow {
                    Text("CheekSquintLeft: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.cheekSquintLeft.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                    Text("CheekSquintRight: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.cheekSquintRight.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                }
            }
            Divider().gridCellUnsizedAxes(.horizontal)
            Group {
                Group {
                    GridRow {
                        Text("MouthLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthSmileLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthSmileLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthSmileRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthSmileRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthUpperUpLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthUpperUpLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthUpperUpRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthUpperUpRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthLowerDownLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthLowerDownLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthLowerDownRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthLowerDownRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthFunnel: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthFunnel.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthPucker: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthPucker.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthClose: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthClose.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("TongueOut: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.tongueOut.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                }
                Divider().gridCellUnsizedAxes(.horizontal)
                Group {
                    GridRow {
                        Text("MouthFrownLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthFrownLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthFrownRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthFrownRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthDimpleLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthDimpleLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthDimpleRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthDimpleRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthStretchLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthStretchLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthStretchRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthStretchRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthRollLower: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthRollLower.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthRollUpper: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthRollUpper.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthShrugLower: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthShrugLower.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthShrugUpper: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthShrugUpper.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                    GridRow {
                        Text("MouthPressLeft: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthPressLeft.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                        Text("MouthPressRight: ")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.trailing)
                        Text("\(arViewModel.faceBlendShapes[FaceBlendShape.mouthPressRight.rawValue], specifier: "%.1f")")
                            .foregroundColor(.secondary)
                            .font(.system(size: 13))
                            .gridColumnAlignment(.leading)
                    }
                }
            }
            Divider().gridCellUnsizedAxes(.horizontal)
            Group {
                GridRow {
                    Text("JawLeft: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.jawLeft.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                    Text("JawRight: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.jawRight.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                }
                GridRow {
                    Text("JawForward: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.jawForward.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                    Text("JawOpen: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.jawOpen.rawValue], specifier: "%.1f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                }
            }
            Divider().gridCellUnsizedAxes(.horizontal)
            Group {
                GridRow {
                    Text("HeadRoll: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.headRoll.rawValue], specifier: "%.2f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                    Text("HeadPitch: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.headPitch.rawValue], specifier: "%.2f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                }
                GridRow {
                    Text("HeadYaw: ")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.trailing)
                    Text("\(arViewModel.faceBlendShapes[FaceBlendShape.headYaw.rawValue], specifier: "%.2f")")
                        .foregroundColor(.secondary)
                        .font(.system(size: 13))
                        .gridColumnAlignment(.leading)
                }
            }
        }
    }
}

struct FaceBlendShapeView_Previews: PreviewProvider {
    static var previews: some View {
        FaceBlendShapeView()
            .environmentObject(ArViewModel())
    }
}
