//
//  RigTestView.swift
//  Blendshape2Robot
//
//  Created by liu on 2023/02/16.
//

import SwiftUI

struct RigTestView: View {
    @EnvironmentObject var arViewModel: ArViewModel
    @FocusState private var onFocused: Bool
    @State private var buttonColor: Color = .blue
    @State private var colorIdx: Int = 0
    @State private var rigIdx: Int = 0
    private let colors: [Color] = [.blue, .brown, .cyan, .green, .indigo,
        .mint, .orange, .purple, .red, .teal, .yellow]
    
    var body: some View {
        VStack {
            Image("nikola-actuators")
                .resizable()
                .scaledToFit()
            HStack {
                Text("Nikola Actuator # ")
                    .foregroundColor(.accentColor)
                    .padding(.leading, 30)
                Spacer()
                Image(systemName: "paperplane")
                    .resizable()
                    .frame(width: 50, height: 50)
                    .foregroundColor(buttonColor)
                    .padding(.trailing, 30)
                    .onTapGesture {
                        arViewModel.request_command_sending()
                        if colorIdx < colors.count - 1 {
                            colorIdx += 1
                        } else {
                            colorIdx = 0
                        }
                        buttonColor = colors[colorIdx]
                    }
                    .onLongPressGesture(minimumDuration: 2.0) {
                        arViewModel.start_rig_test()
                    }
            }
            // Picker doesn't work well with ARKit; wait for next version update
            HStack {
                Text("01")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[0], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("02")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[1], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("03")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[2], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("04")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[3], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("05")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[4], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }.padding([.leading, .trailing])
            HStack {
                Text("06")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[5], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("07")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[6], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("08")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[7], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("09")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[8], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("10")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[9], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }.padding([.leading, .trailing])
            HStack {
                Text("11")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[10], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("12")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[11], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("13")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[12], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("14")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[13], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("15")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[14], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }.padding([.leading, .trailing])
            HStack {
                Text("16")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[15], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("17")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[16], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("18")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[17], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("19")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[18], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("20")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[19], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }.padding([.leading, .trailing])
            HStack {
                Text("21")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[20], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("22")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[21], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("23")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[22], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("24")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[23], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("25")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[24], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }.padding([.leading, .trailing])
            HStack {
                Text("26")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[25], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("27")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[26], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("28")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[27], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("29")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[28], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("30")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[29], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }.padding([.leading, .trailing])
            HStack {
                Text("31")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[30], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("32")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[31], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("33")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[32], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("34")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[33], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                Text("35")
                    .foregroundColor(.secondary)
                TextField("0", value: $arViewModel.nikolaRigs[34], formatter: NumberFormatter())
                    .keyboardType(.numberPad).focused($onFocused)
                    .accentColor(.accentColor)
                    .foregroundColor(Color(UIColor.darkGray))
                    .textFieldStyle(RoundedBorderTextFieldStyle())
            }.padding([.leading, .trailing])

            Spacer()
        }.onTapGesture {
            onFocused = false
        }
    }
}

struct RigTestView_Previews: PreviewProvider {
    static var previews: some View {
        RigTestView()
            .environmentObject(ArViewModel())
    }
}
